"""
HACM Onboarding / Offboarding Service  —  port 8007
=====================================================
Manages the full join/leave lifecycle for human employees AND AI agents.

Odoo hr_onboarding covers:
    Checklists, document collection, system access provisioning,
    welcome emails, buddy assignment, probation tracking.

HACM extends it with:
    - Belief fit assessment at entry (vs org template)
    - Token budget provisioning for day one
    - AI agent onboarding: mandate declaration, guardrail setup,
      RAG seeding from org_memory, belief vector initialization
    - Learning plan generation on day one (from learning service)
    - Offboarding: knowledge capture before departure,
      directed mutation trigger (T_replace_h2a or T_probe_entry),
      AI agent retirement: mandate archival, memory cleanup

Key difference from Odoo:
    Odoo onboards humans. HACM onboards humans AND AI agents,
    and treats both as capital units entering or leaving the org.

    When a human leaves: T_probe_entry may be triggered (outsider injection).
    When an AI agent is retired: correlated failure record is archived,
    and T_replace_a2h may reinstate human oversight in that domain.
"""

import os
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from datetime import date, datetime
from enum import Enum

app = FastAPI(title="HACM Onboarding/Offboarding Service", version="1.0.0")
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])


# ── ENUMS ──────────────────────────────────────────────────────────────

class JourneyState(str, Enum):
    PLANNED     = "planned"
    IN_PROGRESS = "in_progress"
    COMPLETE    = "complete"
    PAUSED      = "paused"
    CANCELLED   = "cancelled"


class JourneyType(str, Enum):
    ONBOARDING  = "onboarding"
    OFFBOARDING = "offboarding"


class UnitType(str, Enum):
    HUMAN    = "human"
    AI_AGENT = "ai_agent"


class TaskStatus(str, Enum):
    PENDING   = "pending"
    COMPLETE  = "complete"
    SKIPPED   = "skipped"
    BLOCKED   = "blocked"


class MutationTrigger(str, Enum):
    """
    Directed mutation events that onboarding/offboarding can trigger.
    Rajendra (2026) §4 — Directed Mutation.
    """
    T_PROBE_ENTRY   = "T_probe_entry"      # new outsider human → inject diversity
    T_REPLACE_H2A   = "T_replace_h2a"     # human replaced by AI agent
    T_REPLACE_A2H   = "T_replace_a2h"     # AI agent replaced by human


# ── TASK TEMPLATES ────────────────────────────────────────────────────
# Dynamically assembled per unit type + role. Not a static catalog.

HUMAN_ONBOARDING_TASKS = [
    # Day 1
    {"code": "H-ON-01", "title": "System access provisioning",
     "day": 1, "owner": "IT", "required": True,
     "description": "Email, Slack, HACM platform access, SSO setup"},
    {"code": "H-ON-02", "title": "Welcome and org orientation",
     "day": 1, "owner": "People", "required": True,
     "description": "Meet your manager, tour the space, team introductions"},
    {"code": "H-ON-03", "title": "HACM belief profile setup",
     "day": 1, "owner": "Self", "required": True,
     "description": "Author your initial belief profile. What do you believe about this work?",
     "hacm_note": "Generates belief_vector for digital twin. No Odoo equivalent."},
    {"code": "H-ON-04", "title": "Meet your AI agents",
     "day": 1, "owner": "Manager", "required": True,
     "description": "Introduction to the AI agents you'll work alongside. What they do, what they don't.",
     "hacm_note": "No Odoo equivalent. Critical for activation velocity."},
    {"code": "H-ON-05", "title": "Token budget activation",
     "day": 1, "owner": "People", "required": True,
     "description": "Your AI capability allocation is live. Here's how to use it.",
     "hacm_note": "Huang (2026) token allocation. No Odoo equivalent."},
    # Week 1
    {"code": "H-ON-06", "title": "Role and mandate clarity session",
     "day": 3, "owner": "Manager", "required": True,
     "description": "What does your role look like now that AI handles some of what it used to?"},
    {"code": "H-ON-07", "title": "First learning plan review",
     "day": 5, "owner": "Manager", "required": True,
     "description": "Review auto-generated learning opportunities based on your agents' current sophistication.",
     "hacm_note": "Learning plan generated by learning service from agent state."},
    {"code": "H-ON-08", "title": "Compliance and data handling",
     "day": 5, "owner": "Legal", "required": True,
     "description": "Privacy, data handling, AI use policy, mandate guardrails"},
    # Week 2-4
    {"code": "H-ON-09", "title": "First 30-day activation check",
     "day": 30, "owner": "Manager", "required": True,
     "description": "Review activation score, belief alignment, token utilization. How is it going?"},
    {"code": "H-ON-10", "title": "Peer belief alignment session",
     "day": 14, "owner": "Team", "required": False,
     "description": "Meet 3 colleagues. Compare belief profiles. Find your overlaps."},
    {"code": "H-ON-11", "title": "Benefits enrollment",
     "day": 7, "owner": "People", "required": True,
     "description": "Health, retirement, other benefits. Standard enrollment process."},
    {"code": "H-ON-12", "title": "Payroll and compensation confirmation",
     "day": 3, "owner": "Finance", "required": True,
     "description": "Confirm salary, token allocation, payment schedule"},
]

AI_AGENT_ONBOARDING_TASKS = [
    {"code": "AI-ON-01", "title": "Mandate declaration",
     "day": 0, "owner": "Engineering", "required": True,
     "description": "Declare the agent's operating mandate. What it does, what it doesn't, what it must escalate.",
     "hacm_note": "Mandate forms the AI agent's belief template equivalent."},
    {"code": "AI-ON-02", "title": "Belief vector initialization",
     "day": 0, "owner": "Engineering", "required": True,
     "description": "Initialize agent belief vector against org template. Bell-shaped distribution (high entropy, broad coverage).",
     "hacm_note": "Rajendra (2026) §3.2.1 — AI agents initialize near 0.5, not polarized like humans."},
    {"code": "AI-ON-03", "title": "Token budget provisioning",
     "day": 0, "owner": "Finance", "required": True,
     "description": "Allocate monthly token budget. Set c_part (coupling cost) and c_rag (retrieval cost).",
     "hacm_note": "B* threshold check: is budget above minimum for positive returns?"},
    {"code": "AI-ON-04", "title": "RAG seeding from org_memory",
     "day": 0, "owner": "Engineering", "required": True,
     "description": "Seed the agent's retrieval index with relevant org memory records from previous epochs.",
     "hacm_note": "T_RAG initialization. Regime C operational learning begins immediately."},
    {"code": "AI-ON-05", "title": "Guardrail configuration",
     "day": 0, "owner": "Legal/Engineering", "required": True,
     "description": "Configure ethical guardrails, escalation thresholds, and correlated failure monitoring (ξ_trust=3)."},
    {"code": "AI-ON-06", "title": "Human team introduction",
     "day": 1, "owner": "Manager", "required": True,
     "description": "Brief the human team: what this agent does, when to trust it, when to escalate."},
    {"code": "AI-ON-07", "title": "First epoch monitoring",
     "day": 7, "owner": "Engineering", "required": True,
     "description": "Review mandate coherence, fitness score, failure flags after first 50 steps."},
    {"code": "AI-ON-08", "title": "Activation velocity check",
     "day": 14, "owner": "Manager", "required": True,
     "description": "Is the agent reaching positive net fitness? Is it above B*? Adjust token budget if needed.",
     "hacm_note": "CPM-A4: Token vs B* — key activation metric."},
]

HUMAN_OFFBOARDING_TASKS = [
    {"code": "H-OFF-01", "title": "Knowledge capture session",
     "day": -14, "owner": "Manager", "required": True,
     "description": "Document tacit knowledge before departure. What does only this person know?",
     "hacm_note": "Prevents transmission failure (Rajendra §3.4). Feeds org_memory."},
    {"code": "H-OFF-02", "title": "Belief profile archival",
     "day": -14, "owner": "People", "required": True,
     "description": "Archive belief vector and profile for org_memory. Captures epistemic contribution.",
     "hacm_note": "Prevents turnover from removing tacit knowledge without meso/macro capture."},
    {"code": "H-OFF-03", "title": "Agent handover planning",
     "day": -7, "owner": "Manager", "required": True,
     "description": "Which AI agents did this person direct? Who takes over? Mandate review needed?"},
    {"code": "H-OFF-04", "title": "Mutation type determination",
     "day": -7, "owner": "People", "required": True,
     "description": "Will this role be refilled by a human (T_probe_entry) or transitioned to AI (T_replace_h2a)?",
     "hacm_note": "Directed mutation trigger. No Odoo equivalent — Odoo has no concept of this."},
    {"code": "H-OFF-05", "title": "Exit belief conversation",
     "day": -3, "owner": "Manager", "required": True,
     "description": "Where did org beliefs and personal beliefs diverge? Honest conversation for org learning."},
    {"code": "H-OFF-06", "title": "System access revocation",
     "day": 0, "owner": "IT", "required": True,
     "description": "Revoke all system access, SSO, HACM platform, agent direction permissions"},
    {"code": "H-OFF-07", "title": "Token budget reallocation",
     "day": 0, "owner": "Finance", "required": True,
     "description": "Redistribute departing person's token allocation to remaining team or new hire.",
     "hacm_note": "No Odoo equivalent. Token budget is a first-class capital item."},
    {"code": "H-OFF-08", "title": "Final payslip and expense clearance",
     "day": 0, "owner": "Finance", "required": True,
     "description": "Final salary, outstanding expenses, token overage or credit settlement"},
]

AI_AGENT_OFFBOARDING_TASKS = [
    {"code": "AI-OFF-01", "title": "Retirement trigger review",
     "day": 0, "owner": "Engineering", "required": True,
     "description": "What triggered retirement? Performance threshold (T_replace_a2h), correlated failure, or planned rotation?",
     "hacm_note": "Rajendra §4 — retirement type determines whether human oversight is reinstated."},
    {"code": "AI-OFF-02", "title": "Mandate archival",
     "day": 0, "owner": "Engineering", "required": True,
     "description": "Archive operating mandate, belief vector, failure history for future reference."},
    {"code": "AI-OFF-03", "title": "Org memory update",
     "day": 0, "owner": "Engineering", "required": True,
     "description": "Write final epoch records to org_memory. Preserve what this agent learned."},
    {"code": "AI-OFF-04", "title": "Failure pattern documentation",
     "day": 0, "owner": "Engineering", "required": True,
     "description": "Document any correlated failures. Were they related to model version, retrieval source, or mandate drift?"},
    {"code": "AI-OFF-05", "title": "Human oversight reinstatement",
     "day": 0, "owner": "Manager", "required": True,
     "description": "Which tasks return to human ownership? Brief the team. Adjust workload.",
     "hacm_note": "T_replace_a2h: human reinstatement after AI retirement. AWS 2024 pattern."},
    {"code": "AI-OFF-06", "title": "Token budget reclamation",
     "day": 0, "owner": "Finance", "required": True,
     "description": "Reclaim remaining token allocation. Redistribute or return to org pool."},
]


# ── IN-MEMORY STORE ───────────────────────────────────────────────────
_journeys: Dict[str, dict] = {}
_counter = {"journey": 0}


# ── SCHEMAS ──────────────────────────────────────────────────────────

class JourneyStartRequest(BaseModel):
    unit_id: str                                # employee_id or agent_id
    unit_name: str
    unit_type: UnitType
    journey_type: JourneyType
    start_date: date
    manager_id: Optional[str] = None
    role: Optional[str] = None
    department: Optional[str] = None

    # Belief state at entry/exit (HACM-only)
    initial_belief_vector: Optional[List[float]] = None
    belief_alignment_at_entry: Optional[float] = None

    # AI agent specific
    mandate_text: Optional[str] = None
    model_version: Optional[str] = None
    monthly_token_allocation: Optional[float] = None

    # Mutation context (for offboarding)
    mutation_trigger: Optional[MutationTrigger] = None
    replacement_type: Optional[str] = None     # "human", "ai_agent", "none"

    custom_tasks: Optional[List[dict]] = None  # extra tasks beyond template


class TaskUpdateRequest(BaseModel):
    journey_id: str
    task_code: str
    status: TaskStatus
    completed_by: Optional[str] = None
    notes: Optional[str] = None


# ── BUSINESS LOGIC ────────────────────────────────────────────────────

def _build_task_list(unit_type: UnitType, journey_type: JourneyType,
                     custom_tasks: Optional[List[dict]] = None) -> List[dict]:
    """Assemble task list from template for this unit type + journey type."""
    template_map = {
        (UnitType.HUMAN, JourneyType.ONBOARDING):    HUMAN_ONBOARDING_TASKS,
        (UnitType.HUMAN, JourneyType.OFFBOARDING):   HUMAN_OFFBOARDING_TASKS,
        (UnitType.AI_AGENT, JourneyType.ONBOARDING): AI_AGENT_ONBOARDING_TASKS,
        (UnitType.AI_AGENT, JourneyType.OFFBOARDING):AI_AGENT_OFFBOARDING_TASKS,
    }
    tasks = [
        {**t, "status": TaskStatus.PENDING.value, "completed_by": None,
         "completed_at": None, "notes": None}
        for t in template_map.get((unit_type, journey_type), [])
    ]
    if custom_tasks:
        tasks.extend([{**t, "status": TaskStatus.PENDING.value,
                       "completed_by": None, "completed_at": None, "notes": None}
                      for t in custom_tasks])
    return sorted(tasks, key=lambda t: t.get("day", 0))


def _compute_progress(tasks: List[dict]) -> dict:
    total = len(tasks)
    required = [t for t in tasks if t.get("required", True)]
    done = [t for t in tasks if t["status"] == TaskStatus.COMPLETE.value]
    req_done = [t for t in required if t["status"] == TaskStatus.COMPLETE.value]
    return {
        "total_tasks": total,
        "completed": len(done),
        "required_total": len(required),
        "required_completed": len(req_done),
        "pct_complete": round(len(done) / max(total, 1) * 100, 1),
        "required_pct": round(len(req_done) / max(len(required), 1) * 100, 1),
        "is_complete": len(req_done) == len(required),
    }


def _activation_velocity(journey: dict) -> dict:
    """
    Estimate activation velocity — how quickly is this unit reaching
    productive contribution? HACM CPM S1 (H+AI Activation Velocity).
    """
    progress = journey["progress"]
    days_in = (date.today() - date.fromisoformat(journey["start_date"])).days
    unit_type = journey["unit_type"]

    # Benchmarks from Rajendra (2026) simulation
    benchmarks = {
        "human":    {"day_1_target": 40, "day_7_target": 65, "day_30_target": 85},
        "ai_agent": {"day_1_target": 80, "day_7_target": 90, "day_30_target": 95},
    }
    bench = benchmarks.get(unit_type, benchmarks["human"])

    current = progress["required_pct"]
    if days_in <= 1:
        target = bench["day_1_target"]
    elif days_in <= 7:
        target = bench["day_7_target"]
    else:
        target = bench["day_30_target"]

    on_track = current >= target
    return {
        "days_in": days_in,
        "current_progress_pct": current,
        "target_pct": target,
        "on_track": on_track,
        "velocity_status": "on track" if on_track else "behind",
        "note": (
            f"{'AI agents activate faster than humans — '  if unit_type == 'ai_agent' else ''}"
            f"{'✓ Activation on track.' if on_track else f'⚠ Behind target. Focus on required tasks first.'}"
        ),
    }


# ── ENDPOINTS ─────────────────────────────────────────────────────────

@app.get("/")
def root():
    return {"service": "onboarding", "port": 8007}

@app.get("/health")
def health():
    return {"status": "up", "service": "onboarding",
            "active_journeys": sum(1 for j in _journeys.values()
                                    if j["state"] == JourneyState.IN_PROGRESS.value)}


@app.post("/journeys")
def start_journey(req: JourneyStartRequest):
    """Start an onboarding or offboarding journey for a human or AI agent."""
    _counter["journey"] += 1
    journey_id = f"JRN-{_counter['journey']:04d}"

    tasks = _build_task_list(req.unit_type, req.journey_type, req.custom_tasks)
    progress = _compute_progress(tasks)

    journey = {
        "journey_id": journey_id,
        "unit_id": req.unit_id,
        "unit_name": req.unit_name,
        "unit_type": req.unit_type.value,
        "journey_type": req.journey_type.value,
        "start_date": str(req.start_date),
        "manager_id": req.manager_id,
        "role": req.role,
        "department": req.department,
        "state": JourneyState.IN_PROGRESS.value,
        "created_at": datetime.utcnow().isoformat(),

        # Belief state
        "initial_belief_vector": req.initial_belief_vector,
        "belief_alignment_at_entry": req.belief_alignment_at_entry,

        # AI agent fields
        "mandate_text": req.mandate_text,
        "model_version": req.model_version,
        "monthly_token_allocation": req.monthly_token_allocation,

        # Mutation context
        "mutation_trigger": req.mutation_trigger.value if req.mutation_trigger else None,
        "replacement_type": req.replacement_type,

        "tasks": tasks,
        "progress": progress,
        "activation_velocity": _activation_velocity({
            "unit_type": req.unit_type.value,
            "start_date": str(req.start_date),
            "progress": progress,
        }),

        # HACM insight
        "hacm_insight": _onboarding_insight(req),
    }
    _journeys[journey_id] = journey
    return journey


@app.get("/journeys")
def list_journeys(unit_type: Optional[str] = None,
                   journey_type: Optional[str] = None,
                   state: Optional[str] = None):
    items = list(_journeys.values())
    if unit_type:   items = [j for j in items if j["unit_type"] == unit_type]
    if journey_type: items = [j for j in items if j["journey_type"] == journey_type]
    if state:       items = [j for j in items if j["state"] == state]
    return {"total": len(items), "journeys": items}


@app.get("/journeys/{journey_id}")
def get_journey(journey_id: str):
    j = _journeys.get(journey_id)
    if not j:
        raise HTTPException(status_code=404, detail="Journey not found")
    # Refresh progress and velocity
    j["progress"] = _compute_progress(j["tasks"])
    j["activation_velocity"] = _activation_velocity(j)
    if j["progress"]["is_complete"]:
        j["state"] = JourneyState.COMPLETE.value
    return j


@app.patch("/journeys/{journey_id}/tasks")
def update_task(journey_id: str, update: TaskUpdateRequest):
    """Mark a task complete, skipped, or blocked."""
    j = _journeys.get(journey_id)
    if not j:
        raise HTTPException(status_code=404, detail="Journey not found")
    task = next((t for t in j["tasks"] if t["code"] == update.task_code), None)
    if not task:
        raise HTTPException(status_code=404, detail=f"Task {update.task_code} not found")
    task["status"] = update.status.value
    task["completed_by"] = update.completed_by
    task["completed_at"] = datetime.utcnow().isoformat() if update.status == TaskStatus.COMPLETE else None
    task["notes"] = update.notes
    j["progress"] = _compute_progress(j["tasks"])
    if j["progress"]["is_complete"]:
        j["state"] = JourneyState.COMPLETE.value
    return {"journey_id": journey_id, "task_code": update.task_code,
            "new_status": update.status.value, "progress": j["progress"]}


@app.get("/journeys/{journey_id}/next-tasks")
def get_next_tasks(journey_id: str, limit: int = 3):
    """Return the next N pending required tasks."""
    j = _journeys.get(journey_id)
    if not j:
        raise HTTPException(status_code=404, detail="Journey not found")
    pending = [t for t in j["tasks"]
               if t["status"] == TaskStatus.PENDING.value and t.get("required", True)]
    return {
        "journey_id": journey_id,
        "next_tasks": pending[:limit],
        "remaining_required": len(pending),
    }


@app.get("/templates")
def get_templates(unit_type: Optional[str] = None, journey_type: Optional[str] = None):
    """Return task templates for given unit type and journey type."""
    all_templates = {
        "human_onboarding": HUMAN_ONBOARDING_TASKS,
        "human_offboarding": HUMAN_OFFBOARDING_TASKS,
        "ai_agent_onboarding": AI_AGENT_ONBOARDING_TASKS,
        "ai_agent_offboarding": AI_AGENT_OFFBOARDING_TASKS,
    }
    if unit_type and journey_type:
        key = f"{unit_type}_{journey_type}"
        return {key: all_templates.get(key, [])}
    return all_templates


@app.get("/summary")
def org_journey_summary():
    journeys = list(_journeys.values())
    active = [j for j in journeys if j["state"] == JourneyState.IN_PROGRESS.value]
    complete = [j for j in journeys if j["state"] == JourneyState.COMPLETE.value]
    human_onboarding = [j for j in active
                         if j["unit_type"] == "human" and j["journey_type"] == "onboarding"]
    ai_onboarding = [j for j in active
                      if j["unit_type"] == "ai_agent" and j["journey_type"] == "onboarding"]
    offboarding = [j for j in active if j["journey_type"] == "offboarding"]
    return {
        "total_journeys": len(journeys),
        "active": len(active),
        "complete": len(complete),
        "human_onboarding_active": len(human_onboarding),
        "ai_agent_onboarding_active": len(ai_onboarding),
        "offboarding_active": len(offboarding),
        "mutations_triggered": [
            j["mutation_trigger"] for j in journeys if j.get("mutation_trigger")
        ],
    }


# ── HACM INSIGHT ──────────────────────────────────────────────────────

def _onboarding_insight(req: JourneyStartRequest) -> dict:
    if req.journey_type == JourneyType.ONBOARDING:
        if req.unit_type == UnitType.AI_AGENT:
            return {
                "title": "AI agent activation begins at day 0",
                "message": (
                    f"Unlike human onboarding (30+ days to full activation), "
                    f"{req.unit_name} begins Regime C operational learning immediately. "
                    f"Token budget must be above B* threshold from day one for positive net fitness."
                ),
                "mutation_note": "T_probe_entry is NOT triggered — this is a new AI agent deployment, not a human outsider injection.",
            }
        else:
            belief_note = ""
            if req.belief_alignment_at_entry is not None:
                if req.belief_alignment_at_entry < 0.5:
                    belief_note = f" Belief alignment at entry is {req.belief_alignment_at_entry:.0%} — below average. Schedule belief conversation early."
                else:
                    belief_note = f" Belief alignment at entry is {req.belief_alignment_at_entry:.0%} — good starting point."
            return {
                "title": "Human onboarding activates the T_probe_entry pattern",
                "message": (
                    f"{req.unit_name} joins as an outsider — their belief vector seeds from an external distribution, "
                    f"not from org_memory. This is deliberate: outsiders inject epistemic diversity the org cannot generate internally."
                    + belief_note
                ),
                "mutation_note": "T_probe_entry fires at scheduled interval. This onboarding is part of that mechanism.",
            }
    else:
        return {
            "title": f"Offboarding triggers knowledge capture and mutation review",
            "message": (
                f"{'Mandate archival and human oversight review required.' if req.unit_type == UnitType.AI_AGENT else 'Tacit knowledge must be captured before departure. Transmission failure is a structural risk (Rajendra §3.4).'}"
            ),
            "mutation_note": f"Mutation trigger: {req.mutation_trigger.value if req.mutation_trigger else 'not yet determined — review required'}",
        }


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=int(os.getenv("SERVICE_PORT", 8007)))
