-- Tessera Database Initialization
CREATE DATABASE tessera_costbenefit;
CREATE DATABASE tessera_payroll;
CREATE DATABASE tessera_learning;
CREATE DATABASE tessera_twin;
CREATE DATABASE tessera_people;
CREATE DATABASE tessera_expenses;
CREATE DATABASE tessera_onboarding;
CREATE DATABASE tessera_identity;
CREATE DATABASE tessera_itsm;
CREATE DATABASE tessera_workos;
CREATE DATABASE tessera_notifications;
CREATE DATABASE tessera_audit;
CREATE DATABASE tessera_timeattendance;
CREATE DATABASE tessera_benefits;
CREATE DATABASE tessera_recruiting;
CREATE DATABASE tessera_performance;
CREATE DATABASE tessera_succession;
CREATE DATABASE tessera_compensation;
CREATE DATABASE tessera_absence;
CREATE DATABASE tessera_workforce;
CREATE DATABASE tessera_finance;
CREATE DATABASE tessera_knowledge;
CREATE DATABASE tessera_catalog;

GRANT ALL PRIVILEGES ON DATABASE tessera_costbenefit  TO tessera;
GRANT ALL PRIVILEGES ON DATABASE tessera_payroll      TO tessera;
GRANT ALL PRIVILEGES ON DATABASE tessera_learning     TO tessera;
GRANT ALL PRIVILEGES ON DATABASE tessera_twin         TO tessera;
GRANT ALL PRIVILEGES ON DATABASE tessera_people       TO tessera;
GRANT ALL PRIVILEGES ON DATABASE tessera_expenses     TO tessera;
GRANT ALL PRIVILEGES ON DATABASE tessera_onboarding   TO tessera;
GRANT ALL PRIVILEGES ON DATABASE tessera_identity     TO tessera;
GRANT ALL PRIVILEGES ON DATABASE tessera_itsm         TO tessera;
GRANT ALL PRIVILEGES ON DATABASE tessera_workos       TO tessera;
GRANT ALL PRIVILEGES ON DATABASE tessera_notifications TO tessera;
GRANT ALL PRIVILEGES ON DATABASE tessera_audit             TO tessera;
GRANT ALL PRIVILEGES ON DATABASE tessera_timeattendance    TO tessera;
GRANT ALL PRIVILEGES ON DATABASE tessera_benefits          TO tessera;
GRANT ALL PRIVILEGES ON DATABASE tessera_recruiting        TO tessera;
GRANT ALL PRIVILEGES ON DATABASE tessera_performance       TO tessera;
GRANT ALL PRIVILEGES ON DATABASE tessera_succession        TO tessera;
GRANT ALL PRIVILEGES ON DATABASE tessera_compensation      TO tessera;
GRANT ALL PRIVILEGES ON DATABASE tessera_absence           TO tessera;
GRANT ALL PRIVILEGES ON DATABASE tessera_workforce         TO tessera;
GRANT ALL PRIVILEGES ON DATABASE tessera_finance           TO tessera;
GRANT ALL PRIVILEGES ON DATABASE tessera_knowledge         TO tessera;
GRANT ALL PRIVILEGES ON DATABASE tessera_catalog           TO tessera;
